version: "3"

services:
  kpz-dev-frontend:
    environment:
      - VITE_BACKEND_URL=${DEV_BACKEND_URL}
      - VITE_PUBLIC_HERE_API_KEY=${VITE_PUBLIC_HERE_API_KEY}
    image: goodbuy/kpz-dev-frontend
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: kpz-dev-frontend-container
