version: "3"

services:
  kpz-prod-frontend:
    image: goodbuy/kpz-prod-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: kpz-prod-frontend-container
