# api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: locationservice-service
spec:
  selector:
    app: locationservice
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30002 # Choose a NodePort value (e.g., 30000) or let Kubernetes allocate one automatically.
