services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run local