version: '3'

services:
  express-typescript-docker-dev:
    image: goodbuy/kpz:dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    container_name: express-typescript-docker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev