version: '3'

services:
  express-typescript-docker-prod:
    image: goodbuy/kpz:prod
    environment:
      - NODE_ENV=production
    expose:
      - '3001'
    ports:
      - '3001:3000'
    command: node dist/index.js