apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-setup
spec:
  template:
    spec:
      containers:
        - name: mongo-init
          image: mongo:latest
          command: ["mongo"]
          args:
            [
              "mongo-service/admin",
              "--eval",
              "db.getSiblingDB('kita_data').createCollection('kitadetail')",
            ]
      restartPolicy: OnFailure
  backoffLimit: 3 # The number of retries before considering the Job as failed
