AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist
      Handler: functions/index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          SLACK_TOKEN: xoxe.xoxp-1-Mi0yLTE7NDM3Njg4NzkyNy0yMzQ2NDA5OTQ1NzctNTM5OTkxMzYwNzg3NS01NDAwMDM5MTk3MzE0LTcyYTI4ZGMwYzQyN2U1NzJjNjA2NDM0OTQ5MGYyYzNlZTRjNmE0YWZmNDhkZDE4Y2NjZDA0YjU4ZDBkMmE0NzM
          SLACK_CHANNEL_ID: C05BF4NNU94
