# my-app-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-secrets
data:
  AWS_KMS_KEY_ID: { { .Values.AWS_KMS_KEY_ID } }
  API_KEY: { { .Values.API_KEY } }
  AUTH_KEY: { { .Values.AUTH_KEY } }
  AWS_ACCESS_KEY_ID: { { .Values.AWS_ACCESS_KEY_ID } }
  AWS_SECRET_ACCESS_KEY: { { .Values.AWS_SECRET_ACCESS_KEY } }
  MONGO_DB_CONNECTION: { { .Values.MONGO_DB_CONNECTION } }
  ANOTHER_SECRET: { { .Values.ANOTHER_SECRET } }
