apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "email-chart.fullname" . }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "email-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "email-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretRefName }}
          # volumeMounts:  # If you need to mount volumes, add them here
          #   - name: volume-name
          #     mountPath: /path/to/mount
          #     readOnly: true  # Optional, set to true if read-only
      # Add init containers, volumes, etc. if necessary
