apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice-deployment
spec:
  replicas: 1 # Number of desired replicas (adjust as needed)
  selector:
    matchLabels:
      app: notificationservice
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      containers:
        - name: notificationservice-container
          image: public.ecr.aws/b2z0n9v4/kpz-notification-k8ts:v1.0
          ports:
            - containerPort: 3000 # Replace with the port your API listens on
          envFrom:
            - secretRef:
                name: my-secrets
          env:
            - name: SLACK_WEBHOOK_ERROR_URL
              value: "https://hooks.slack.com/services/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"
            - name: SLACK_WEBHOOK_SIGNUP_URL
              value: "https://hooks.slack.com/services/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"
          # volumeMounts:  # If you need to mount volumes, add them here
          #   - name: volume-name
          #     mountPath: /path/to/mount
          #     readOnly: true  # Optional, set to true if read-only
          # Add more container settings if required
      # Add init containers, volumes, etc. if necessary
