apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.ports.amqp }}
    - name: management
      port: {{ .Values.ports.management }}
