apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-cronjob
spec:
  schedule: "0 0 * * 0" # This schedule runs the job at 00:00 (midnight) on Sundays (day 0 of the week)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scraper
              image: public.ecr.aws/b2z0n9v4/kpz-scraper-k8ts:latest # Replace this with the image of your scraper
              command: ["node"]
              args: ["index.js"]
              # Add any environment variables or other configuration needed for your scraper here
          restartPolicy: OnFailure # Change this to OnFailure if you want to retry on failure
