apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper
          image: public.ecr.aws/b2z0n9v4/kpz-scraper-k8ts:latest # Replace with the image of your scraper
          command: ["node"]
          args: ["index.js"]
          # Add any environment variables or other configuration needed for your scraper here
      # Add any other settings, volumes, and configurations needed for your scraper
