## GitHub Actions Workflow to push to static website S3 bucket on master branch merge

name: Deploy Frontend to Production

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:


permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: arn:aws:iam::897331788878:role/github_actions_role_v2
            role-session-name: GitHubActionsS3
            aws-region: eu-central-1

      - name: Install dependencies
        run: yarn --cwd "frontend" install

      - name: Build
        run: yarn --cwd "frontend" build

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: frontend/dist
          VITE_BACKEND_URL: ${{ vars.BACKEND_URL }}
          VITE_PUBLIC_HERE_API_KEY: ${{ secrets.VITE_PUBLIC_HERE_API_KEY }}
          bucket: ${{ vars.S3_BUCKET }}
          bucket-region: ${{ vars.S3_BUCKET_REGION }}
          dist-id: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
