name: Deploy Dev Backend to EC2

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'

jobs:
  deploy-dev-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clone or Pull KPZ Repo Dev Branch
        uses: appleboy/ssh-action@master
        with:
          host: 3.70.176.52
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if [ ! -d "kpz_dev" ]; then
              echo "Cloning repository: KitaPlatzZentrale/kpz"
              git clone -b dev git@github.com:KitaPlatzZentrale/kpz.git kpz_dev
              cd kpz_dev
            else
              cd kpz_dev
              echo "Repository KitaPlatzZentrale/kpz already exists, pulling the latest changes"
              git pull origin dev
            fi

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image Backend Dev
        working-directory: ./backend
        run: docker build -t goodbuy/kpz-dev-backend .

      - name: Push Docker Image
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push goodbuy/kpz-dev-backend

      - name: Deploy Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: 3.70.176.52
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd kpz/backend
            docker-compose -f docker-compose.dev.yml down
            docker rm kpz-dev-backend-container
            docker rmi goodbuy/kpz-dev-backend
            docker-compose -f docker-compose.dev.yml up -d
