name: Deploy Prod Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy-prod-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clone or Pull KPZ Repo
        uses: appleboy/ssh-action@master
        with:
          host: 3.70.176.52
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if [ ! -d "kpz" ]; then
              echo "Cloning repository: KitaPlatzZentrale/kpz"
              git clone git@github.com:KitaPlatzZentrale/kpz.git
              cd kpz
            else
              cd kpz
              echo "Repository KitaPlatzZentrale/kpz already exists, pulling the latest changes"
              git pull
            fi
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image Backend Prod
        working-directory: ./backend
        run: docker build -t goodbuy/kpz-prod-backend .

      - name: Push Docker Image
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push goodbuy/kpz-prod-backend

      - name: Deploy Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: 3.70.176.52
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd kpz/backend
            docker-compose down --remove-orphans
            docker rm kpz-prod-backend-container
            docker rmi goodbuy/kpz-prod-backend
            docker-compose -f docker-compose.prod.yml up -d
