name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Docker Image Dev
      run: docker build -f backend/Dockerfile.dev -t goodbuy/kpz:dev .
      
    - name: Build Docker Image Prod
      run: docker build -f backend/Dockerfile.prod -t goodbuy/kpz:prod .

    - name: Push Docker Image
      run: |
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push goodbuy/kpz:dev
        docker push goodbuy/kpz:prod

    - name: Deploy Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: 3.70.176.52
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          git pull
          docker-compose down
          docker-compose up -d
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
          
