apiVersion: apps/v1
kind: Deployment
metadata:
  name: locationservice-deployment
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app: locationservice
  template:
    metadata:
      labels:
        app: locationservice
    spec:
      containers:
        - name: locationservice-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.env.secretRefName }}

          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
      # Add init containers, volumes, etc. if necessary
